### ISSUE TITLE
Well of knowledge crash

### ISSUE THREAD

**Issue by Zen9890** [TrashboxBobylev/Summoning-Pixel-Dungeon#56]
Happened when i drank from well of knowledge with unidentified dirk in hands
***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: samsung
Device: a23
Model: SM-A235F
Manufacturer: samsung
Product: a23nsxx
SDK: 33
Release: 13

***** APP INFO 
Version: 1.2.4-76d5772
Installed On: 2023-01-29 07:10:04
Updated On: 2023-02-14 07:30:41
Current Date: 2023-02-14 07:45:30

***** ERROR LOG 
java.lang.NullPointerException: Attempt to invoke virtual method 'com.shatteredpixel.shatteredpixeldungeon.items.Item com.shatteredpixel.shatteredpixeldungeon.items.artifacts.Artifact.identify()' on a null object reference
	at com.shatteredpixel.shatteredpixeldungeon.actors.hero.Belongings.observe(Belongings.java:250)
	at com.shatteredpixel.shatteredpixeldungeon.actors.blobs.WaterOfAwareness.affectHero(WaterOfAwareness.java:53)
	at com.shatteredpixel.shatteredpixeldungeon.actors.blobs.WellWater.affect(WellWater.java:67)
	at com.shatteredpixel.shatteredpixeldungeon.actors.blobs.WellWater.affectCell(WellWater.java:129)
	at com.shatteredpixel.shatteredpixeldungeon.levels.Level.pressCell(Level.java:1016)
	at com.shatteredpixel.shatteredpixeldungeon.levels.Level.occupyCell(Level.java:978)
	at com.shatteredpixel.shatteredpixeldungeon.actors.Char.move(Char.java:879)
	at com.shatteredpixel.shatteredpixeldungeon.actors.hero.Hero.move(Hero.java:2036)
	at com.shatteredpixel.shatteredpixeldungeon.actors.hero.Hero.getCloser(Hero.java:1601)
	at com.shatteredpixel.shatteredpixeldungeon.actors.hero.Hero.actMove(Hero.java:887)
	at com.shatteredpixel.shatteredpixeldungeon.actors.hero.Hero.act(Hero.java:789)
	at com.shatteredpixel.shatteredpixeldungeon.actors.Actor.process(Actor.java:270)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.GameScene$2.run(GameScene.java:576)

***** END OF LOG *****

**Comment by sjsxmd** [comment]
***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: HONOR
Device: HWJSN-HM
Model: JSN-AL00a
Manufacturer: HUAWEI
Product: JSN-AL00a
SDK: 29
Release: 10

***** APP INFO 
Version: 1.2.4a-e6d90b7
Installed On: 2023-07-13 19:06:30
Updated On: 2023-07-13 19:06:30
Current Date: 2023-07-13 22:19:35

***** ERROR LOG 
java.lang.NullPointerException: Attempt to invoke virtual method 'com.shatteredpixel.shatteredpixeldungeon.items.Item com.shatteredpixel.shatteredpixeldungeon.items.artifacts.Artifact.identify()' on a null object reference
	at com.shatteredpixel.shatteredpixeldungeon.actors.hero.Belongings.observe(Belongings.java:250)
	at com.shatteredpixel.shatteredpixeldungeon.actors.blobs.WaterOfAwareness.affectHero(WaterOfAwareness.java:53)
	at com.shatteredpixel.shatteredpixeldungeon.actors.blobs.WellWater.affect(WellWater.java:67)
	at com.shatteredpixel.shatteredpixeldungeon.actors.blobs.WellWater.affectCell(WellWater.java:129)
	at com.shatteredpixel.shatteredpixeldungeon.levels.Level.pressCell(Level.java:1016)
	at com.shatteredpixel.shatteredpixeldungeon.levels.Level.occupyCell(Level.java:978)
	at com.shatteredpixel.shatteredpixeldungeon.actors.Char.move(Char.java:894)
	at com.shatteredpixel.shatteredpixeldungeon.actors.hero.Hero.move(Hero.java:2031)
	at com.shatteredpixel.shatteredpixeldungeon.actors.hero.Hero.getCloser(Hero.java:1596)
	at com.shatteredpixel.shatteredpixeldungeon.actors.hero.Hero.actMove(Hero.java:882)
	at com.shatteredpixel.shatteredpixeldungeon.actors.hero.Hero.act(Hero.java:784)
	at com.shatteredpixel.shatteredpixeldungeon.actors.Actor.process(Actor.java:270)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.GameScene$2.run(GameScene.java:576)



***** END OF LOG *****

**Comment by TrashboxBobylev** [comment]
This is actually fixed in 1.2.5 snapshots, augh....
